DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    title TEXT NOT NULL ,
    author TEXT NOT NULL ,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER [UpdateField] AFTER UPDATE ON [books]
BEGIN
    UPDATE books SET updated = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;
